services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./BACKEND/.env
    environment:
      - DJANGO_DEBUG=True
    volumes:
      - ./BACKEND:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./FRONTEND/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND/frontend:/app
    command: npm run dev -- --host 0.0.0.0
