# Generated by Django 5.2 on 2025-08-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='etiquitas_pac',
            new_name='etiquetas_pac',
        ),
    ]
